language: objective-c

before_install:
        - sudo gem update --system
        - sudo gem install cocoapods
        - cd Example/Objective-C
        - pod install
        - cd ../Swift
        - pod install
        - cd ..

script:
        - xcodebuild build -workspace Objective-C/AddressBook.xcworkspace -scheme AddressBook -destination 'platform=iOS Simulator,name=iPhone 5,OS=latest'
